FROM openjdk:8-jre-alpine
COPY ./target/reactive-todo-list-app-1.0.0-SNAPSHOT.jar /usr/src/todo-list-application/
WORKDIR /usr/src/todo-list-application
CMD ["java", "-jar", "reactive-todo-list-app-1.0.0-SNAPSHOT.jar"]
