FROM openjdk:8-jre-alpine
COPY ./target/todo-list-application-1.0.0-SNAPSHOT.jar /usr/src/todo-list-application/
WORKDIR /usr/src/todo-list-application
CMD ["java", "-jar", "todo-list-application-1.0.0-SNAPSHOT.jar"]
